### ISSUE TITLE
Please get rid of the "I see five icons dialog"

### ISSUE THREAD

**Issue by rsmarples** [m00nyONE/HodorReflexes#4]
It's impossible to click on steam deck without docking a keyboard and mouse and disabling the console ui entirely and I have to do this each update. Just remove it please.

hodor works fine otherwise.

**Comment by m00nyONE** [comment]
i will think about a different solution maybe. But i will not get rid of it because it's the only indication that the update worked... Many people have problems with minion not updating all files, and this dialog shows if something is wrong.

Maybe there is a way i can implement some sort of keybind to close it like a normal menu

**Comment by m00nyONE** [comment]
in version 2024.08.25 there is now a keybind that you can set to close the dialog
